version: 2.1

jobs:
  lint_format_test:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Requirements
          command: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run:
          name: Black Format Check
          command: black --check ace/
      - run:
          name: Unit tests
          command: pytest -v -m unit
      - run:
          name: Integration Tests
          command: pytest -v -m integration
      - run:
          name: System Tests
          command: pytest -v -m system

workflows:
  version: 2.1
  lint_format_test:
    jobs:
      - lint_format_test
